# Generated by Django 2.2.7 on 2020-02-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.BigIntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.BigIntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Technical Skills',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.BigIntegerField(editable=False, unique=True)),
                ('job_name', models.CharField(max_length=50)),
                ('job_description', models.TextField(max_length=1000)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('max_exp', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('min_exp', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skill', to='jobs.TechnicalSkills')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.BigIntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('resume', models.FileField(upload_to='media')),
                ('skill', models.ManyToManyField(to='jobs.TechnicalSkills')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
