# Generated by Django 2.2.7 on 2020-02-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200211_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='max_exp',
            field=models.DecimalField(decimal_places=4, default='', max_digits=4),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='min_exp',
            field=models.DecimalField(decimal_places=4, default='', max_digits=4),
        ),
    ]
