# Generated by Django 2.2.7 on 2020-02-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200211_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='max_exp',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='min_exp',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
