# Generated by Django 2.2.7 on 2020-02-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200211_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='max_exp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='min_exp',
            field=models.FloatField(),
        ),
    ]
